# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 'pypy3.9'
      - run: python -V
      - run: echo " pip poetry  "
      - run: pip install poetry
      - run: pip install protobuf==4.21
      - run: poetry install --no-root
      - run: ./compile.sh
      - run: pytest
#
#          compile.sh
#          python install grpcio
#          python install grpcio-tools
#          pytest
#          python server.py > /dev/null 2>&1 &
#          python client.py
#          kill -9 $(lsof -t -i:5001)
