# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run:
          python -V
          echo " pip poetry  "
          pip install poetry
          echo " poetry install "
          poetry install 
          echo " compile "
          compile.sh
          python install grpcio
          python install grpcio-tools
          pytest
          python server.py > /dev/null 2>&1 &
          python client.py
          kill -9 $(lsof -t -i:5001)
