# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 'pypy3.9'
      - run: |
          pip install grpcio==1.51.3
          pip install grpcio-tools==1.48.2
          mkdir -p ./chat/proto
          cp ./protos/__init__.py ./chat/proto/__init__.py
          python -m grpc_tools.protoc --proto_path=./protos/ --python_out=./chat/proto --grpc_python_out=./chat/proto ./protos/chat.proto
          python setup.py sdist bdist_wheel
          cp ./dist/chat-0.0.1-py3-none-any.whl ./chat-0.0.1-py3-none-any.whl
          pip install --force-reinstall chat-0.0.1-py3-none-any.whl
          pip install pytest
      - run: ls ./chat/proto
      - run: python main.py
      - run: pytest
      - run: python server.py > /dev/null 2>&1 &
      - run: python client.py
      - run: kill -9 $(lsof -t -i:5001)
